info:
  contact: {}
  title: Curanest API for EXE201
  version: "1.0"
paths:
  /users/hello:
    get:
      consumes:
      - application/json
      description: hello
      produces:
      - application/json
      responses:
        "200":
          description: say hi
          schema:
            type: string
      summary: hello
      tags:
      - users
swagger: "2.0"
